---
# tasks to install the conda package manager

- stat: path="{{ conda_parent_dir }}/conda/bin/conda"
  become: no
  register: conda_binary

- name: create conda parent directory
  become: no
  file: path="{{ conda_parent_dir }}" state=directory
  when: conda_binary.stat.exists == False

- name: download linux miniconda install
  become: no
  get_url:
    url: "{{ linux_miniconda_installer_url }}"
    dest: "/tmp/miniconda_install.sh"
  when: conda_binary.stat.exists == False and ( ansible_os_family == "Debian" or ansible_os_family == "RedHat" )

- name: download macos miniconda install
  become: no
  get_url:
    url: "{{ macos_miniconda_installer_url }}"
    dest: "/tmp/miniconda_install.sh"
  when: conda_binary.stat.exists == False and ansible_os_family == "Darwin"

- name: run miniconda installer
  become: no
  shell: bash /tmp/miniconda_install.sh -b -p "{{ conda_parent_dir }}/conda"
  args:
    creates: "{{ conda_parent_dir }}/conda/bin/conda }}"
  when: conda_binary.stat.exists == False

- name: add conda path to path in .profile
  become: no
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    line: "if [ -e \"$HOME/{{ conda_rel_path }}/conda/bin/conda\" ]; then export PATH=\"$HOME/{{ conda_rel_path }}/conda/bin:$PATH\"; fi   # added by freckles"
    create: yes
  when: conda_binary.stat.exists == False and add_path | default(true)
  ignore_errors: true


- name: update conda
  become: no
  shell: "{{ conda_parent_dir }}/conda/bin/conda update --name root conda"
  when: conda_binary.stat.exists == False
